part1: day1_part1.cpp
	g++ -O2 -o part1 day1_part1.cpp

part1_debug: day1_part1.cpp
	g++ -g -o part1 day1_part1.cpp

run1: part1
	./part1

part2: day1_part2.cpp
	g++ -O2 -o part2 day1_part2.cpp

part2_debug: day1_part2.cpp
	g++ -g -O0 -o part2 day1_part2.cpp

run2: part2
	./part2

clean:
	rm -f part1 part2